project_id = "coyqbspjryohkccxnkti"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.otp-request]
    verify_jwt = false
  [functions.otp-verify]
    verify_jwt = false
  [functions.send-otp-resend]
    verify_jwt = false
  [functions.verify-otp-resend]
    verify_jwt = false
  [functions.request-password-reset]
    verify_jwt = false
  [functions.resend-webhook]
    verify_jwt = false
  [functions.import-sql]
    verify_jwt = false
